앱마무리5차 12.15/app_allergy/app_allergy/allergykitprojectdj/allergykitmain/urls.py
from . import views
#from rest_framework import routers
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'allergykitmain'

urlpatterns = [
    path('', views.main, name='main'),
    path('AL/logingo', views.loginpage, name="logingo"),
    path('AL/login', views.login, name="login"),
    path('AL/FindUsr', views.findusr, name="findusr"),
    path('AL/SignUpGo', views.signupgo, name="signupgo"),
    path('AL/SignUp', views.SignUp, name="SignUp"),

    path('AL/FindIDgo', views.find_id_go, name="find_id_go"),
    path('AL/FindPWgo', views.find_pw_go, name="find_pw_go"),

    path('AL/FindID', views.find_id, name="find_id"),
    path('AL/FindPW', views.find_pw, name="find_pw"),
    path('AL/Menu_choice', views.back_to_main, name="menu_choice"),
    #시트지 선택
    path('AL/Choice_Sheet', views.choice_sheet_paper, name="choice_sheet"),
    #사진 촬영
    path('AL/Take_Picture', views.take_pic, name="take_pic"),
    #사진 분석
    path('AL/Pic_Analysis', views.opencv_pic, name="opencv_pic"),
    #상세결과
    path('AL/Detail_result/<allergy_id>', views.inspection_detail_result, name="inspection_detail_result"),
    path('AL/Detail_result/<allergy_id>/<allergy_kinds>', views.detail_result, name="detail_result"),

    # 결과 조회 및 확인
    path('AL/Lookup_result', views.lookup_result, name="lookup_result"),
    #ajax
    path('ajax/idcheck', views.SignUp_idcheck, name="SignUp_idcheck"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

앱마무리5차 12.15/app_allergy/app_allergy/allergykitprojectdj/allergykitproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("allergykitmain.urls")),
]

앱마무리5차 12.15/app_allergy/app_allergy/allergykitprojectdj/allergykitmain/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    al_ID = models.CharField(max_length=20, null=True, blank=False)
    al_PW = models.CharField(max_length=20, null=True, blank=False)
    al_Name = models.CharField(max_length=20, null=True, blank=False)
    al_Email = models.CharField(max_length=50, null=True, blank=False)
    al_Birth = models.CharField(max_length=50, null=True, blank=False)
    al_Height = models.CharField(max_length=50, null=True, blank=False)
    al_Weight = models.CharField(max_length=50, null=True, blank=False)
    al_Gender = models.CharField(max_length=1, null=True, blank=False) #0=man, 1=woman

class UsrAllergy(models.Model):
    User_Allergy = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=False)
    Al_CreateDate = models.DateTimeField(null=True, blank=False)
    Al_Files = models.FileField(null=True, blank=True)
    fish_al = models.CharField(max_length=6, default=0)
    flour_al = models.CharField(max_length=6, default=0)
    milk_al = models.CharField(max_length=6, default=0)
    meat_al = models.CharField(max_length=6, default=0)
    fruit_al = models.CharField(max_length=6, default=0)
    cheese_al = models.CharField(max_length=6, default=0)
    alcohol_al = models.CharField(max_length=6, default=0)
    egg_al = models.CharField(max_length=6, default=0)
    chicken_al = models.CharField(max_length=6, default=0)
    vegetable_al = models.CharField(max_length=6, default=0)

    class Meta:
        get_latest_by = ['Al_CreateDate']

앱마무리5차 12.15/app_allergy/app_allergy/allergykitprojectdj/allergykitmain/views.py
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import *
from datetime import datetime
import json, random, string
from .forms import *
from django.utils import timezone
from django.utils.encoding import smart_text
from django.core.files.storage import FileSystemStorage
from django.views.generic import UpdateView
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
#이메일 관련 import
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from .tokens import AccountActivationTokenGenerator
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text

#opencv
import cv2 as cv
import numpy as np

# 세션 관리
def addSessions(request, user):
    request.session['al_id'] = user.al_ID
    request.session['al_name'] = user.al_Name

# 접속자의 유저 객체 반환
def getInfo(request):
    user = User.objects.get(al_ID=request.session['al_id'])
    return user

#메인 페이지
def main(request):
    return render(request, 'allergykitmain/main.html')

#로그인
def loginpage(request):
    return render(request, 'allergykitmain/login/login.html')

def login(request):
    if request.method == 'POST':
        user_id = request.POST['al_id']
        user_pw = request.POST['al_pw']
        try:
            user = User.objects.get(al_ID=user_id)
            if user_pw == user.al_PW:
                addSessions(request, user)    
                return render(request, 'allergykitmain/menu/menu_choice.html', {
                    'user_info' : user,
                    })
            elif user_pw != user.al_PW:
                return render_to_response('allergykitmain/Error/Error.html', {
                    'alert_msg' : '비밀번호가 맞지 않습니다.',
                    'url' : '/'
                })
        except User.DoesNotExist:
            return render_to_response('allergykitmain/Error/Error.html', {
                    'alert_msg' : '해당 아이디가 없습니다.',
                    'url' : '/'
                })
    else:
        return render(request, 'allergykitmain/login/login.html', {
            'user_info' : getInfo(request),
             })

#유저정보찾기
def findusr(request):
    return render(request, 'allergykitmain/findusr/findusrinfo.html')

#회원가입
def signupgo(request):
    return render(request, 'allergykitmain/signup/signup.html')

#회원 가입
def SignUp(request):
    if request.method == "POST":
        #성별
        gendercheck = request.POST['usr_gender']
        
        user = User.objects.create(
        al_ID = request.POST['al_id'],
        al_PW = request.POST['al_pw'],
        al_Name = request.POST['al_name'],
        al_Gender = gendercheck,
        al_Email = request.POST['al_email'],
        al_Birth = request.POST['al_birth'],
        al_Height = request.POST['al_height'],
        al_Weight = request.POST['al_weight'],
        )
        return render(request, 'allergykitmain/login/login.html')

    return render(request, 'allergykitmain/signup/signup.html')


#회원가입시 유저 id 중복 방지
def SignUp_idcheck(request):
    id_check = request.POST['idcheck']
    UserList = User.objects.filter(al_ID=id_check)
    if not UserList:
        context = {  'msg' : 'Y',  }
    else:
        context = {  'msg' : 'N',  }

    return HttpResponse(json.dumps(context), content_type="application/json")

#아이디 비밀번호 찾기 이동
def find_id_go(request):
    return render(request, 'allergykitmain/findusr/find_usr_id.html')

def find_pw_go(request):
    return render(request, 'allergykitmain/findusr/find_usr_pw.html')

#아이디 비밀번호 찾기 기능
def find_id(request):
    try:
        user = User.objects.get(al_Name=request.POST['al_name'], al_Email=request.POST['al_email'])
        message = render_to_string('allergykitmain/findusr/find_usr_id_email.html',{
                'user': user,
        })
        mail_subject = "[알레르기케어 키트]] 아이디 찾기 메일입니다."
        user_email = user.al_Email
        email = EmailMessage(mail_subject, message, to=[user_email])
        email.send()
        return render(request, 'allergykitmain/login/login.html')
    except Exception as e:
        print(e)
        messages.error(request, '해당하는 정보의 아이디가 없습니다.')
        return redirect('allergykitmain:find_id_go')
    
def find_pw(request):
    try:
        user = User.objects.get(al_Name=request.POST['al_name'], al_ID=request.POST['al_id'], al_Email=request.POST['al_email'])
        
        _LENGTH = 12 # 12자리
        # 숫자 + 대소문자
        string_pool = string.ascii_letters + string.digits
        # 랜덤한 문자열 생성
        update_usr_pw = "" 
        for i in range(_LENGTH) :
            update_usr_pw += random.choice(string_pool) # 랜덤한 문자열 하나 선택
        User.objects.filter(al_Name=request.POST['al_name']).filter(al_ID=request.POST['al_id']).filter(al_Email=request.POST['al_email']).update(
            al_PW = update_usr_pw,
        )
        message = render_to_string('allergykitmain/findusr/find_usr_pw_email.html', {
            'user_pw':update_usr_pw,
        })
        mail_subject = "[알레르기케어 키트] 임시 비밀번호 메일입니다."
        user_email = user.al_Email
        email = EmailMessage(mail_subject, message, to=[user_email])
        email.send()
        return render(request, 'allergykitmain/login/login.html')
    except:
        messages.error(request, '해당하는 정보의 회원이 없습니다.')
        return redirect('allergykitmain:find_pw_go')

#시트지 선택 페이지
def choice_sheet_paper(request):
    user = User.objects.get(al_ID=request.session['al_id'])
    return render(request, 'allergykitmain/inspection/sheet_paper_choice.html', {'user_info': user,}) 

#사진 촬영 페이지
def take_pic(request):
    user = User.objects.get(al_ID=request.session['al_id'])
    return render(request, 'allergykitmain/inspection/img_preview.html', {'user_info': user,}) 

#사진 저장 및 opencv
def opencv_pic(request):
    try:
        user = User.objects.get(al_ID=request.session['al_id'])
        allergy_arr=[]
        arr_dict={
            1:{'fish_al':0},
            2:{'fish_al':0, 'flour_al':0},
            3:{'fish_al':0, 'flour_al':0, 'milk_al':0},
            4:{'fish_al':0, 'flour_al':0, 'milk_al':0, 'meat_al':0},
            5:{'fish_al':0, 'flour_al':0, 'milk_al':0, 'meat_al':0, 'fruit_al':0},
            6:{'fish_al':0, 'flour_al':0, 'milk_al':0, 'meat_al':0, 'fruit_al':0,'cheese_al':0},
            7:{'fish_al':0, 'flour_al':0, 'milk_al':0, 'meat_al':0, 'fruit_al':0,'cheese_al':0, 'alcohol_al':0},
            8:{'fish_al':0, 'flour_al':0, 'milk_al':0, 'meat_al':0, 'fruit_al':0,'cheese_al':0, 'alcohol_al':0, 'egg_al':0},
            9:{'fish_al':0, 'flour_al':0, 'milk_al':0, 'meat_al':0, 'fruit_al':0,'cheese_al':0, 'alcohol_al':0, 'egg_al':0, 'chicken_al':0},
            10:{'fish_al':0, 'flour_al':0, 'milk_al':0, 'meat_al':0, 'fruit_al':0,'cheese_al':0, 'alcohol_al':0, 'egg_al':0, 'chicken_al':0, 'vegetable_al':0},
        }
        if request.method == 'POST': # method가 POST 방식이라면 글이 써진 것
            usr_allergy = UsrAllergy.objects.create(
                User_Allergy = user,
                Al_CreateDate = datetime.now(),
                Al_Files = request.FILES['camera']
            )
            img = cv.imread("./media/"+str(usr_allergy.Al_Files))
            img = cv.resize(img,dsize=(600, 800), interpolation=cv.INTER_AREA)
            height, width, _ = img.shape

            roi = img[int(height/6*1):height, int(width/4*1):int(width/4*3)]

            roi_gray = cv.cvtColor(roi, cv.COLOR_BGR2GRAY)

            kernel = np.ones((5, 5))
            test_img = cv.Canny(roi_gray, 60, 150)
            test_img = cv.morphologyEx(test_img, cv.MORPH_CLOSE, kernel)

            j = 0
            nlabels, _, stats, __ = cv.connectedComponentsWithStats(test_img)

            for i in range(nlabels):

                if i < 2:
                    continue
                width = stats[i, cv.CC_STAT_WIDTH]
                height = stats[i, cv.CC_STAT_HEIGHT]

                ratio = width/height
                if width < 100 and height < 100 and width > 10 and height > 10 and ratio > 0.4 and ratio < 2 and j < 10:
                    j += 1
                    allergy_arr.append(round(width*height,2)/100)
            
            index=0
            try:
                for key in arr_dict[j]:
                    arr_dict[j][key]=allergy_arr[index]
                    index += 1
            except:
                messages.error(request, '사진을 다시 찍어주세요.')
                return redirect('allergykitmain:take_pic')

            UsrAllergy.objects.filter(id=usr_allergy.id).update(
                **arr_dict[j]
            )
            max_count = 0
            for a in allergy_arr:
                if a>=40:
                    max_count += 1

            return render(request, 'allergykitmain/inspection/inspection_result.html', {'user_info': user, 'usr_allergy':usr_allergy, 'allergy_count':j,'danger_allergy':max_count, 'allergy_list':arr_dict[j],})
    except:
        messages.error(request, '사진을 찍고 결과를 분석해주세요!')
        return redirect('allergykitmain:take_pic')
    return render(request, 'allergykitmain/inspection/img_preview.html', {'user_info': user,})

#상세 결과 페이지
def inspection_detail_result(request, allergy_id):
    user = User.objects.get(al_ID=request.session['al_id'])
    usr_allergy_info = UsrAllergy.objects.get(id=allergy_id)
    return render(request, 'allergykitmain/inspection/inspection_detail_result.html', {'user_info': user, 'usr_allergy_info':usr_allergy_info,}) 

#상세 결과 
def detail_result(request, allergy_id, allergy_kinds):
    user = User.objects.get(al_ID=request.session['al_id'])
    usr_allergy_info = UsrAllergy.objects.get(id=allergy_id)
    if allergy_kinds == '1':
        fish_result = float(usr_allergy_info.fish_al)

앱마무리5차 12.15/app_allergy/app_allergy/allergykitprojectdj/allergykitmain/templates/allergykitmain/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--나눔고딕-->
<link href="https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap" rel="stylesheet">
<!--오류 발생 알람메시지-->
{% if messages %}
    {% for message in messages %} 
        <script>alert("{{message}}");</script>
    {% endfor %}
{% endif %}
<!--알람 끝-->
</head>
<style>
    body{
        font-family: 'NanumSquare', sans-serif;
        margin:0px;
        padding:0px;
        width:100%;
        height:100vh;
        background : no-repeat center/100vh url('/static/allergykitmain/img/loginmain.png');
    }
    input[type=password] {
        font-family: 'Nanum Gothic', sans-serif;;
        
        &::placeholder {
        	font-family: "NanumSquare", sans-serif;;
        }
    }

</style>
<body>
<form action="{% url 'allergykitmain:login' %}" method="POST" style="width:100%; margin:0px; padding:0px;">
{% csrf_token %}
    <div class="container-fluid" style="width:100%;">
        <div class="row" style="padding-top:35%;">    
            <div style="width:100%; text-align:center; font-size:40px;">
                welcome
            </div>
            <div style="width:100%; text-align:center; padding-top:5%;">
                <img style="width:20%;" src="{% static 'allergykitmain/img/people.png'%}">
            </div>
            
            <div class="col-sm-2" style="width:15%; margin-left:12%; margin-top:5%; border-top:2px solid #c8c8c8; border-bottom:2px solid #c8c8c8; border-left:2px solid #c8c8c8; border-radius:20px 0px 0px 20px; background:rgb(21,21,21);">
            </div>
            <div class="col-sm-10 from-group" style="width:60%; background-color:#FFFFFF; margin-top:5%; border:2px solid #c8c8c8; border-radius:0px 20px 20px 0px;">
                <input type="text" id="al_id" name="al_id" class="form-control" maxlength="20" placeholder="Username" style="width:100%; border: none; border-color: transparent;">
            </div>
            <div class="col-sm-2" style="width:15%; margin-left:12%; margin-top:5%; border-top:2px solid #c8c8c8; border-bottom:2px solid #c8c8c8; border-left:2px solid #c8c8c8; border-radius:20px 0px 0px 20px; background:rgb(21,21,21);">
            </div>
            <div class="col-sm-10 from-group" style="width:60%; margin-top:5%; background-color:#FFFFFF; border:2px solid #c8c8c8; border-radius:0px 20px 20px 0px;">
                <input type="password" id="al_pw" name="al_pw" class="form-control" maxlength="20" placeholder="Password" style="width:100%; border: none; border-color: transparent;">
            </div>
            <div class="row" style="width:100%; padding-left:22%;">
                <div class="col-sm-3" style="width:30%; padding-top:1.5%;">
                    <a href="{% url 'allergykitmain:signupgo' %}" style="text-decoration: none; color:rgb(21,21,21); font-size:13px; cursor:pointer;">Join</a>
                </div>
                <div class="col-sm-9" style="width:70%; padding-left:15%; padding-top:1.5%;">
                    <a href="{% url 'allergykitmain:findusr' %}" style="text-decoration: none; color:rgb(21,21,21); font-size:13px; cursor:pointer;">Forgot Password?</a>
                </div>
            </div>
            <div style="font-size:18px; width:100%; padding-left:60%; margin-top:5%;">
                Login<input class="btn btn-success" type="submit" value=" " style="width:30%; height:3.5vh; margin-left:2%; color:rgb(30,74,34); border-radius:12px 12px 12px 12px;">
            </div>
            </form>
            <div style="width:100%; padding-left:40vw; margin-top:20%;">
                <img src="{% static 'allergykitmain/img/logo.png' %}" style="height:10vh;">
            <div>
        </div>
    </div>
</body>
</html>